#!/usr/bin/env bash
# Upstream watch: after a promotion, ask a Claude agent what the port implies
# for the patch set, and act on it. The promoted binary is already live by the
# time it runs, so anything it changes lands on the next port of this version.
#
#   advisory-agent.sh <version> <stock-suite-log>
#
# Two questions. What has phate45/claude-patching — the project that pioneered
# this approach, and still the best source of new patch ideas — done since we
# last looked. And what does the stock run of our own suite say about patches
# Claude Code may have made redundant.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$ROOT/lib.sh"
if ! is_porter; then
  echo "advisory-agent.sh runs only on porter $(<"$ROOT/porter")" >&2
  exit 1
fi
STATE="$ROOT/port-state"
VER="${1:?usage: advisory-agent.sh <version> <stock-suite-log>}"
STOCK_LOG="${2:?usage: advisory-agent.sh <version> <stock-suite-log>}"
VERSIONS="$HOME/.local/share/claude/versions"
mkdir -p "$STATE"
PROMPT="$STATE/advisory-$VER.prompt"
REVIEWED="$STATE/phate45-reviewed"

cat > "$PROMPT" <<EOF
You are the upstream watch for this Claude Code patching repository. Claude Code
$VER has just been patched and promoted. Work out what that implies for the
patch set, and act on it.

## 1. What upstream has done

phate45/claude-patching pioneered this approach and is still worth watching.
Shallow-fetch it into a temp directory and review the commits after
$(cat "$REVIEWED" 2>/dev/null || echo "<no SHA recorded — review the last 20 commits>"):

    git clone --filter=blob:none https://github.com/phate45/claude-patching "\$(mktemp -d)/upstream"

Look for: patches worth adopting here (we would rewrite them from our own
anchors, never copy their code — that repository has no license), anchoring
techniques better than ours, and retirements or advisories on patches we still
carry. Their retirement of quiet-notifications is the model case: an upstream
note that a patch had become harmful was worth acting on immediately.

When you are done, write upstream's current tip SHA to $REVIEWED, so the next
run reviews only what is new.

## 2. What the stock run says

The same suite that gated this promotion was run against the stock $VER binary,
where every test is meant to fail:

$(cat "$STOCK_LOG")

A test that PASSES on stock has lost its discrimination. That is a flag, not a
verdict, and it has three possible causes worth telling apart:

- Anthropic shipped the behavior natively. The patch is redundant; it should be
  retired.
- The assertion drifted vacuous — some unrelated change now satisfies it. The
  test needs strengthening, and until it is strengthened its pass on the
  patched candidate proves nothing, so treat that patch as ungated.
- A flake. Say so, and say what makes you think so.

The mirror case needs the failure reasons, not just the counts. A test that
asserts a patch artifact — the CLAUDE_MCP_PER_AGENT canary, a defer stub's
text — can never pass on stock even if Anthropic has fixed the underlying
problem. Read each stock failure reason and say which ones mean "the behavior
is still broken without us" and which mean "the artifact is simply absent, and
the behavior may well be fixed". Check the $VER release notes for anything that
would confirm the latter.

## 3. What to do about it

If nothing is actionable, finish with a one-line summary and stop.

If anything is actionable — a patch Anthropic made redundant, a vacuous test,
an upstream patch worth adopting, an upstream advisory that a patch we carry is
harmful — spawn one Fable subagent (Agent tool, model "fable") with your full
diagnosis and the evidence behind it. Fable is the decision-maker: it decides
what to change and delegates the implementation to its own Opus subagents
(Agent tool, model "opus"). Do what Fable decides and nothing more.

Several machines share this repository, so Fable runs \`git pull --rebase
origin master\` before editing anything, and \`git push origin master\` after
each commit that passes the gate.

Every edit is gated the same way the port gates one. Build a candidate with
\`./apply-display-patches.sh $VER <tmp>\` and run \`tests/run-all.sh <candidate>
<skip-ids>\` before committing, where <skip-ids> is the contents of
patches-local/$VER/dropped plus every patches/*.mjs id absent from
\`./apply-display-patches.sh --print-ids\`. Commit in logical units, with the
rationale in the message: a retired patch with its test and its line in
apply-display-patches.sh; a new patch with its test; a strengthened test on its
own. Changing patches/ alters the patch-set fingerprint, so the next launch or
watch event re-ports and re-gates this version on its own; that is expected.

Tell Fable that if it decides something needs a human, reporting it is its own
job: open a GitHub issue on ahalekelly/claude-patching with the full detail
(\`gh issue create\`, with the "🤖 Generated by Claude Code" line at the top),
then deliver one paragraph with \`./brief.sh "<paragraph>"\` — what the problem
is, what the human must do, and the issue URL. That paragraph opens in a
Terminal window and is printed again at the next launch, and it is the only
thing the owner reads.

Do not touch anything in $VERSIONS.
EOF

exec "$ROOT/agent-run.sh" "$VER" advisory opus "$PROMPT" 30
