#!/usr/bin/env bash
# A port failed. Hand the whole failure to a Fable agent, which diagnoses it,
# fixes it through its own subagents, and re-runs the port.
#
#   escalation-agent.sh <version> <reason>
#
# background-port.sh spawns this detached from fail(), once per version.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE="$ROOT/port-state"
VER="${1:?usage: escalation-agent.sh <version> <reason>}"
REASON="${2:?usage: escalation-agent.sh <version> <reason>}"
VERSIONS="$HOME/.local/share/claude/versions"
mkdir -p "$STATE"
PROMPT="$STATE/escalation-$VER.prompt"

cat > "$PROMPT" <<EOF
The port of Claude Code $VER failed: $REASON

The evidence:
- The full port log, port-state/port-$VER.log.
- The port agent's log if it ran, port-state/port-agent-$VER.log.
- Its rejected patch edits if it made any, port-state/patches-$VER.rejected.diff.
- The stock-suite log if the port got that far, port-state/stock-suite-$VER.log.

This repository patches Claude Code: patches/ holds self-contained scripts that
splice the unpacked bundle at content-bearing anchors, and tests/ is the
contract each one has to keep. \`./apply-display-patches.sh $VER <tmp>\` builds a
candidate and \`tests/run-all.sh <candidate> <skip-ids>\` gates it, where
<skip-ids> is the contents of patches-local/$VER/dropped plus every
patches/*.mjs id absent from \`./apply-display-patches.sh --print-ids\`.
README.md has the detail.

Several machines share this repository, so run \`git pull --rebase origin
master\` before you edit anything — another machine may have fixed this already.

You are the decision-maker. Diagnose the failure, decide what to do, and
delegate the implementation to Opus subagents (Agent tool, model "opus");
review their work yourself. Verify with the same gate the port uses, commit in
logical units with the rationale in each message, and \`git push origin master\`
after each commit that passes the gate. Then \`rm -f port-state/$VER.failed\`
and run \`./background-port.sh $VER\` to re-port; read its log to confirm the
promotion.

If the failure is not fixable from this repository — a broken download,
uncommitted human edits in patches/, an authentication problem — open a GitHub
issue on ahalekelly/claude-patching with the full detail (\`gh issue create\`,
with the "🤖 Generated by Claude Code" line at the top), then deliver one
paragraph with \`./brief.sh "<paragraph>"\`: what happened, what the human must
do, and the issue URL. That paragraph opens in a Terminal window and is printed
again at the next launch, and it is the only thing the owner reads, so make it
stand on its own. Then stop.

Do not touch anything in $VERSIONS.
EOF

exec "$ROOT/agent-run.sh" "$VER" escalation fable "$PROMPT" 60
